name: TEMPLATE-PAYMENTS - Code Review

on:
  push:
    branches: [ main, uat, develop ]
  pull_request:
    types: [ opened, edited, synchronize ]
    branches: [ main, uat, develop ]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  code-review:
    name: Code Review & Quality Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests & Coverage
        id: tests
        run: ./gradlew clean build jacocoTestReport --info

      - name: SonarCloud Analysis
        id: sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
          -Dorg.gradle.jvmargs=-Xmx4096M \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=${{ vars.SONARCLOUD_ORG }} \
          -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }} \
          -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}" \
          -Dsonar.sources=src/main \
          -Dsonar.tests=src/test \
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
          -Dsonar.exclusions='**/enums/**, **/model/**, **/dto/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java' \
          -Dsonar.qualitygate.wait=true

      # Separati gli artifact per test e coverage
      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.run_id }}
          path: build/reports/tests/
          retention-days: 7
          
      - name: Save Coverage Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ github.run_id }}
          path: build/reports/jacoco/
          retention-days: 7

      # Job separato per il merge degli artifact
      - name: Merge Reports
        if: always()
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-reports-${{ github.run_id }}
          pattern: '*-reports-${{ github.run_id }}'
          retention-days: 7

      - name: Create Code Review Summary
        if: always()
        run: |
          echo "## Code Review Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Test Results Location" >> $GITHUB_STEP_SUMMARY
          echo "Test reports are available in artifact: test-reports-${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "### Coverage Results Location" >> $GITHUB_STEP_SUMMARY
          echo "Coverage reports are available in artifact: coverage-reports-${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "### Combined Reports" >> $GITHUB_STEP_SUMMARY
          echo "All reports are available in artifact: all-reports-${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "### Sonar Analysis" >> $GITHUB_STEP_SUMMARY
          echo "Check SonarCloud dashboard for detailed analysis" >> $GITHUB_STEP_SUMMARY